# Generated by Django 6.0.6 on 2026-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('static_image', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(default='BOS Optics Team', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
